### PR TITLE
Add lock details method for battery info

### PR DESCRIPTION
**Pull request by techyowl**
Adds a new method that returns more details about a lock on the August API including the desired battery value. The sooner we can land this or something like this in a new NPM version the sooner I can close out a feature issue with my home bridge august smart locks repo. Battery level is a useful metric to be able to monitor in addition to its lock state. Because the endpoint isn't battery specific I opted for the "Details" naming convention

### CODE REVIEW

**Comment by ryanblock** [comment]
Overall this looks good, can you add an integration test? See: https://github.com/ryanblock/august-connect/blob/master/test/integration/src/_lock-unlock-test.js

**Comment by techyowl** [comment]
> Overall this looks good, can you add an integration test? See: https://github.com/ryanblock/august-connect/blob/master/test/integration/src/_lock-unlock-test.js

Done

**Comment by ryanblock** [comment]
Hey, sorry I let this sit, I clearly lost track. Would you be amenable to making edits to make it mergeable, or are you just maintaining your own fork from here on out?

**Comment by techyowl** [comment]
> Hey, sorry I let this sit, I clearly lost track. Would you be amenable to making edits to make it mergeable, or are you just maintaining your own fork from here on out?

I don't use august locks anymore I switched to level locks so I don't have a means to test anything I did anymore. What I worked on, works for some users but not everyone and I think it has to do with using the closed API more than anything. I gave up on it.

**Comment by ryanblock** [comment]
Ah, bummer. Thanks for the swing! Will close for now, and if anyone in the future wants to reopen and try to get it across the finish line, happy to take a look!

**Comment by techyowl** [comment]
I guess I'm a little confused with what needed to be changed to be able to merge my pr? At the time I wrote my pr I followed through and tested every change done to add the battery status to your repo. I was able to read battery values just fine for my august pro locks paired with the connect modules. That's why I created my own npm module with my pr version because it was tested and did work. I had been waiting for you to merge the pr for a few months so I gave up and made my own npm module with the pr code because users of my other HomeKit library were having issues with the library at the time due to it cloning a GitHub repo. I still think that was largely user error installing homebridge as root but I made the npm module to solve their issue. My HomeKit library is what users complain with not this pr changes that were fully tested on their own. 

I see no reason to not merge this pr and I can update my library to use the correct and original npm module(this module) 

The users that had issues seemed to be related to my homebridge library and authenticating with the api. It had nothing to do with this pr and most likely their issues were user error.

**Comment by ryanblock** [comment]
Well, as the PR stands it changes the package name, npm scope, author, GitHub URL, and readme to all point to your repo, which is why I asked if you were amenable to making changes to it to make it mergeable. In the follow up you let me know that the PR didn't work for some users (without any additional context), which signaled to me that this probably wasn't mergeable anyway, so I think given all the above closing this PR made sense. Now it sounds like you are confident in merging it?

**Comment by techyowl** [comment]
Sorry, I am confident in the small changes I made to this pr. I would say my fork has changes I need to revert to let you merge the actual feature addition that has been added without all of the npm changes I added. It has been a busy day for me today being Easter and all so I apologize for not clarifying my message from this morning until now. The battery info was being read from august and it was readable. The main thing I was concerned about was that you needed more testing than what I did over a year ago now when you asked about integration tests which I completed back then. I have the august locks in storage but I don't have a door to install them on 😅 so testing is difficult to say the least. 

So if all you need is the pr reverted back to the tested and merge ready state I can do that for you. 

You closed it with the information you had available to you, I see nothing wrong with that.

**Comment by ryanblock** [comment]
Sounds good! Please feel free to publish those changes and I'll merge away.

**Comment by techyowl** [comment]
> Sounds good! Please feel free to publish those changes and I'll merge away.

It should be good to land now, thanks for checking in on this PR today.

**Comment by ryanblock** [comment]
Looking good. I think the only thing left is documentation in the readme?

**Comment by techyowl** [comment]
> Looking good. I think the only thing left is documentation in the readme?

Does that documentation work?

**Comment by ryanblock** [comment]
Looking like docs are in conflict now: the method is `details()`, and the docs you just pushed are for `battery()`.

**Comment by techyowl** [comment]
> Looking like docs are in conflict now: the method is `details()`, and the docs you just pushed are for `battery()`.

Good catch. That should be fixed now.

**Pull request merged**
